export interface BettingAgent {
  id: string;
  name: string;
  nameHe: string;
  logo: string;
  description: string;
  rating: number;
  bonus: string;
  features: string[];
  pros: string[];
  cons: string[];
  sports: string[];
  minDeposit: string;
  paymentMethods: string[];
  license: string;
  website: string;
  isAvailableInIsrael: boolean;
  legalStatus: string;
  category: "legal" | "international" | "crypto";
  yearFounded?: number;
  headquarters?: string;
}

export const bettingAgents: BettingAgent[] = [
  {
    id: "winner",
    name: "Winner / Toto",
    nameHe: "וינר / טוטו",
    logo: "W",
    description:
      "הפלטפורמה החוקית היחידה להימורי ספורט בישראל. מופעלת על ידי המועצה להסדר ההימורים בספורט (מל\"ה). מציעה הימורי ספורט קבועים ושבועיים, כולל טוטו. פועלת מאז 1967 ולאחרונה עברה מהפכה דיגיטלית עם אתר ואפליקציה מחודשים.",
    rating: 3.5,
    bonus: "בונוס הצטרפות עד ₪200",
    features: [
      "חוקי לחלוטין בישראל",
      "אתר ואפליקציה בעברית מלאה",
      "הפקדה ומשיכה בשקלים",
      "תמיכה בעברית 24/7",
      "טוטו שבועי",
    ],
    pros: [
      "הפלטפורמה החוקית היחידה בישראל",
      "תמיכה מלאה בעברית",
      "הפקדות ומשיכות בשקלים",
      "ממשק מחודש",
    ],
    cons: [
      "אודס נמוכים יחסית לפלטפורמות בינלאומיות",
      "מבחר ספורט ושווקים מוגבל",
      "פחות שווקים חיים (in-play)",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "כדוריד", "כדורעף"],
    minDeposit: "₪10",
    paymentMethods: ["כרטיס אשראי", "העברה בנקאית", "ארנק דיגיטלי", "PayPal"],
    license: "רישיון מל\"ה - מדינת ישראל",
    website: "https://www.winner.co.il",
    isAvailableInIsrael: true,
    legalStatus: "חוקי - הפלטפורמה היחידה המורשית בישראל",
    category: "legal",
    yearFounded: 1967,
    headquarters: "תל אביב, ישראל",
  },
  {
    id: "bet365",
    name: "Bet365",
    nameHe: "בט365",
    logo: "365",
    description:
      "אחד מאתרי ההימורים הגדולים והמוכרים בעולם עם למעלה מ-90 מיליון לקוחות ב-150+ מדינות. מציע מגוון עצום של ספורט, שידורים חיים, Cash Out מוקדם, ואודס תחרותיים מאוד. ממשק מתקדם ואפליקציה מעולה.",
    rating: 4.8,
    bonus: "עד $100 בונוס הצטרפות",
    features: [
      "שידורי ספורט חיים (Live Streaming)",
      "Cash Out מוקדם - חלקי ומלא",
      "אפליקציה מתקדמת iOS/Android",
      "הימורים בזמן אמת עם אודס דינמי",
      "מגוון שווקים עצום (+200 ליגות)",
      "Bet Builder - בנה הימור משולב",
    ],
    pros: [
      "אודס מהגבוהים בשוק",
      "שידורים חיים למשחקים",
      "ממשק אינטואיטיבי ומתקדם",
      "מגוון ספורט ושווקים ענק",
      "Cash Out גמיש",
    ],
    cons: [
      "לא זמין רשמית בישראל",
      "אין תמיכה בעברית",
      "דורש אימות זהות ארוך",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "קריקט", "NFL", "MLB", "NHL", "MMA/UFC", "סנוקר", "גולף", "רוגבי", "כדורעף", "אי-ספורט"],
    minDeposit: "$10",
    paymentMethods: ["Visa", "Mastercard", "PayPal", "Skrill", "Neteller", "העברה בנקאית", "Apple Pay"],
    license: "UK Gambling Commission, MGA Malta, Gibraltar",
    website: "https://www.bet365.com",
    isAvailableInIsrael: false,
    legalStatus: "לא זמין רשמית - ישראל חסומה",
    category: "international",
    yearFounded: 2000,
    headquarters: "סטוק-און-טרנט, אנגליה",
  },
  {
    id: "stake",
    name: "Stake",
    nameHe: "סטייק",
    logo: "S",
    description:
      "פלטפורמת הימורים מבוססת קריפטו מהמובילות בעולם. חסות רשמית של UFC, Everton FC, ו-Drake. מציעה הימורי ספורט וקזינו עם מטבעות דיגיטליים. משיכות מיידיות ואנונימיות. בבעלות Easygo Gaming.",
    rating: 4.5,
    bonus: "בונוס הפקדה ראשונה 200%",
    features: [
      "הימורים בקריפטו - 20+ מטבעות",
      "משיכות מיידיות ללא עמלות",
      "קזינו מובנה + Stake Originals",
      "VIP Club עם הטבות אקסקלוסיביות",
      "ספורט + אי-ספורט + קזינו",
      "ממשק מודרני ומהיר",
    ],
    pros: [
      "משיכות מהירות בקריפטו",
      "ממשק מודרני ומעוצב",
      "בונוסים נדיבים ותכנית VIP",
      "אנונימיות גבוהה",
      "מגוון משחקי קזינו",
    ],
    cons: [
      "לא חוקי בישראל",
      "רק קריפטו - אין פיאט",
      "אין תמיכה בעברית",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "MMA/UFC", "אי-ספורט", "NFL", "הוקי", "בייסבול", "קריקט"],
    minDeposit: "$1 בקריפטו",
    paymentMethods: ["Bitcoin", "Ethereum", "Litecoin", "Dogecoin", "USDT", "XRP", "BNB", "MATIC"],
    license: "Curacao eGaming License",
    website: "https://stake.com",
    isAvailableInIsrael: false,
    legalStatus: "ישראל חסומה - שימוש דרך VPN",
    category: "crypto",
    yearFounded: 2017,
    headquarters: "קוראסאו",
  },
  {
    id: "pinnacle",
    name: "Pinnacle",
    nameHe: "פינאקל",
    logo: "P",
    description:
      "ידועה כבית ההימורים עם האודס הגבוהים ביותר בשוק. מכוונת למהמרים מקצועיים ואינה מגבילה חשבונות מנצחים - מדיניות ייחודית בתעשייה. אחת הפלטפורמות הבודדות שעדיין מקבלות שחקנים ישראלים.",
    rating: 4.6,
    bonus: "אין בונוס - מפצים באודס הגבוהים ביותר",
    features: [
      "האודס הגבוהים בשוק - מוכח מחקרית",
      "לא מגבילים מנצחים - מדיניות ייחודית",
      "אי-ספורט מוביל עולמית",
      "מודל עסקי שקוף - מרווח נמוך",
      "מקבל שחקנים ישראלים",
    ],
    pros: [
      "אודס הגבוהים ביותר בתעשייה",
      "מקבלים מהמרים מקצועיים",
      "זמין לשחקנים ישראלים",
      "אי-ספורט מעולה",
      "שקיפות מלאה",
    ],
    cons: [
      "אין בונוסים כלל",
      "אין שידורים חיים",
      "ממשק פונקציונלי אך פשוט",
      "פחות שווקים אקזוטיים",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "אי-ספורט", "הוקי", "בייסבול", "MMA/UFC", "כדורגל אמריקאי"],
    minDeposit: "$10",
    paymentMethods: ["Visa", "Mastercard", "Skrill", "Neteller", "Bitcoin", "USDT", "ecoPayz"],
    license: "Curacao eGaming License",
    website: "https://www.pinnacle.com",
    isAvailableInIsrael: true,
    legalStatus: "מקבל שחקנים ישראלים",
    category: "international",
    yearFounded: 1998,
    headquarters: "קוראסאו",
  },
  {
    id: "1xbet",
    name: "1xBet",
    nameHe: "וואן אקס בט",
    logo: "1X",
    description:
      "אחת מפלטפורמות ההימורים הגדולות בעולם עם נוכחות חזקה באסיה, אפריקה ומזרח אירופה. מציעה מגוון שווקים עצום שכולל אירועים מיוחדים, פוליטיקה, ומזג אוויר. שותפה רשמית של FC Barcelona.",
    rating: 4.2,
    bonus: "עד $130 בונוס הצטרפות",
    features: [
      "מגוון שווקים ענק - הכי רחב בשוק",
      "שידורים חיים למשחקים נבחרים",
      "אפליקציה מתקדמת ומהירה",
      "קזינו מובנה + משחקים מיידיים",
      "הימורים על אי-ספורט ואירועים מיוחדים",
      "Cash Out זמין",
    ],
    pros: [
      "מגוון ספורט ושווקים הכי רחב",
      "בונוסים נדיבים",
      "אפשרויות תשלום מגוונות מאוד",
      "הימורים על כמעט הכל",
    ],
    cons: [
      "ממשק עמוס ומורכב",
      "תהליך אימות ארוך",
      "תמיכה לפעמים איטית",
      "רגולציה פחות חזקה",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "הוקי", "MMA/UFC", "בייסבול", "אי-ספורט", "פוליטיקה", "כדורעף", "שחמט", "סנוקר"],
    minDeposit: "$1",
    paymentMethods: ["Visa", "Mastercard", "Skrill", "Neteller", "Bitcoin", "Ethereum", "WebMoney", "Perfect Money"],
    license: "Curacao eGaming License",
    website: "https://1xbet.com",
    isAvailableInIsrael: false,
    legalStatus: "זמינות משתנה - בדקו עדכונים",
    category: "international",
    yearFounded: 2007,
    headquarters: "קוראסאו",
  },
  {
    id: "cloudbet",
    name: "Cloudbet",
    nameHe: "קלאודבט",
    logo: "CB",
    description:
      "פלטפורמת הימורי קריפטו ותיקה ואמינה שפועלת מאז 2013. מציעה הימורי ספורט, קזינו חי ומשחקי קריפטו. ידועה באודס תחרותיים, משיכות מהירות, ו-API פתוח למפתחים.",
    rating: 4.3,
    bonus: "עד 5 BTC בונוס הפקדה ראשונה",
    features: [
      "הימורי קריפטו ותיקים ואמינים",
      "קזינו חי עם דילרים אמיתיים",
      "API פתוח וחינמי למפתחים",
      "אודס תחרותיים",
      "Play Euros - משחק ללא סיכון",
      "למעלה מ-30 מטבעות קריפטו",
    ],
    pros: [
      "פלטפורמה ותיקה ואמינה מאז 2013",
      "משיכות מהירות בקריפטו",
      "API חינמי ומתועד",
      "אודס טובים",
      "מבחר קריפטו רחב",
    ],
    cons: [
      "רק קריפטו - אין אפשרות פיאט",
      "ממשק טוב אך לא מהמתקדמים",
      "פחות שווקים מ-Bet365 או 1xBet",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "MMA/UFC", "אי-ספורט", "קריקט", "רוגבי", "כדורעף"],
    minDeposit: "0.001 BTC",
    paymentMethods: ["Bitcoin", "Ethereum", "USDT", "USDC", "Litecoin", "Dogecoin", "Bitcoin Cash", "DAI"],
    license: "Curacao eGaming License, Montenegro Gambling Authority",
    website: "https://www.cloudbet.com",
    isAvailableInIsrael: false,
    legalStatus: "בדקו זמינות עדכנית",
    category: "crypto",
    yearFounded: 2013,
    headquarters: "קוראסאו",
  },
  {
    id: "888sport",
    name: "888sport",
    nameHe: "888 ספורט",
    logo: "888",
    description:
      "חלק מקבוצת 888 Holdings שנוסדה בישראל. אחת מחברות ההימורים הגדולות והמוכרות בעולם, נסחרת בבורסת לונדון. מציעה מגוון ספורט רחב, ממשק ידידותי ובונוסים נדיבים. למרות מוצאה הישראלי, אינה פועלת בישראל.",
    rating: 4.1,
    bonus: "עד $30 הימור חינם",
    features: [
      "חברה ישראלית המקור - נסחרת בלונדון",
      "ממשק ידידותי ונקי",
      "פוקר וקזינו באותה פלטפורמה (888poker)",
      "הימורים חיים מתקדמים",
      "אפליקציה מעולה",
    ],
    pros: [
      "חברה מוכרת ואמינה",
      "ממשק נקי וקל לשימוש",
      "888poker - פוקר אונליין מוביל",
      "רגולציה חזקה (UK, MGA)",
    ],
    cons: [
      "לא זמין בישראל",
      "אודס ממוצעים",
      "פחות שווקים מ-Bet365",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "MMA/UFC", "בייסבול", "כדורגל אמריקאי", "הוקי", "גולף"],
    minDeposit: "$10",
    paymentMethods: ["Visa", "Mastercard", "PayPal", "Apple Pay", "Skrill", "Neteller"],
    license: "UK Gambling Commission, MGA Malta, Gibraltar",
    website: "https://www.888sport.com",
    isAvailableInIsrael: false,
    legalStatus: "לא זמין בישראל למרות מוצא ישראלי",
    category: "international",
    yearFounded: 1997,
    headquarters: "גיברלטר (נוסדה בהרצליה)",
  },
  {
    id: "unibet",
    name: "Unibet",
    nameHe: "יוניבט",
    logo: "UB",
    description:
      "חלק מקבוצת Kindred Group השבדית. פלטפורמה אירופית מוכרת עם דגש על הימורים אחראיים ושקיפות. מציעה ספורט, קזינו ופוקר. ידועה בממשק נקי ובכלי סטטיסטיקה מתקדמים.",
    rating: 4.0,
    bonus: "עד €40 הימור חינם",
    features: [
      "כלי סטטיסטיקה מתקדמים מובנים",
      "דגש על הימורים אחראיים",
      "ממשק נקי ואלגנטי",
      "בלוג ותוכן מקצועי",
      "שידורים חיים נבחרים",
    ],
    pros: [
      "חברה אירופית אמינה ושקופה",
      "כלי ניתוח מובנים",
      "מדיניות הימורים אחראיים מובילה",
      "ממשק נעים",
    ],
    cons: [
      "אודס לא הגבוהים ביותר",
      "פחות שווקים אקזוטיים",
      "זמינות לא יציבה לישראלים",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "הוקי", "גולף", "כדורגל אמריקאי", "רוגבי"],
    minDeposit: "€10",
    paymentMethods: ["Visa", "Mastercard", "Skrill", "Neteller", "Trustly", "PayPal"],
    license: "UK Gambling Commission, MGA Malta, Swedish Gambling Authority",
    website: "https://www.unibet.com",
    isAvailableInIsrael: false,
    legalStatus: "זמינות לא יציבה - בדקו עדכונים",
    category: "international",
    yearFounded: 1997,
    headquarters: "מאלטה (Kindred Group - שבדיה)",
  },
  {
    id: "betway",
    name: "Betway",
    nameHe: "בטוויי",
    logo: "BW",
    description:
      "פלטפורמה בינלאומית ידועה וחסותנית גדולה בעולם הספורט (West Ham, אי-ספורט). מציעה ממשק נקי, אפליקציה מעולה, ושוק אי-ספורט מהמובילים בתעשייה.",
    rating: 4.3,
    bonus: "עד $30 הימור חינם",
    features: [
      "חסות ספורט גדולות - West Ham, אי-ספורט",
      "ממשק נקי ומודרני",
      "אי-ספורט מוביל עולמית",
      "Betway Plus - תכנית נאמנות",
      "Cash Out זמין",
      "אפליקציה מעולה",
    ],
    pros: [
      "חברה מוכרת ואמינה",
      "אי-ספורט מעולה",
      "ממשק נקי ופשוט",
      "אפליקציה מתקדמת",
    ],
    cons: [
      "לא זמין בישראל",
      "בונוסים לא הנדיבים ביותר",
      "פחות שווקים מ-Bet365",
    ],
    sports: ["כדורגל", "כדורסל", "טניס", "אי-ספורט", "קריקט", "רוגבי", "NFL", "NHL"],
    minDeposit: "$10",
    paymentMethods: ["Visa", "Mastercard", "PayPal", "Skrill", "Neteller", "Apple Pay"],
    license: "UK Gambling Commission, MGA Malta",
    website: "https://www.betway.com",
    isAvailableInIsrael: false,
    legalStatus: "לא זמין בישראל",
    category: "international",
    yearFounded: 2006,
    headquarters: "מאלטה",
  },
];

export const agentCategories = {
  legal: { label: "מורשה בישראל", color: "#16a34a" },
  international: { label: "בינלאומי", color: "#1a365d" },
  crypto: { label: "קריפטו", color: "#7c3aed" },
};
